name: Deploy to production ssh rsync

on:
#  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          EXCLUDES: --exclude .htaccess --exclude /uploads/
          USER seland.org
          HOST: ssh.seland.org
          LOCALPATH: /currentbuild/
          REMOTEPATH: /customers/4/3/6/seland.org/httpd.www/hl7/ig
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
